catalogMode: prefer

ignoreWorkspaceRootCheck: true

shellEmulator: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - semver@6.3.1
  - undici-types@6.21.0
  - langium@3.3.1
packages:
  - playground
  - docs
  - packages/*
  - examples/*
catalogs:
  dev:
    '@antfu/eslint-config': ^7.7.3
    '@antfu/ni': ^28.2.0
    baseline-browser-mapping: ^2.10.0
    bumpp: ^10.4.1
    eslint: ^10.0.2
    lint-staged: ^16.3.2
    publint: ^0.3.18
    simple-git: ^3.32.3
    simple-git-hooks: ^2.13.1
    tsdown: ^0.17.3
    tsx: ^4.21.0
    typescript: ^5.9.3
    vite: ^7.3.1
  examples:
    '@slidev/cli': ^52.14.1
  inlined:
    '@antfu/utils': ^9.3.0
  prod:
    '@clack/prompts': ^1.1.0
    cac: ^7.0.0
    gray-matter: ^4.0.3
    picocolors: ^1.1.1
    tinyglobby: ^0.2.15
    unconfig: ^7.5.0
    xdg-basedir: ^5.1.0
    yaml: ^2.8.2
  testing:
    tinyexec: ^1.0.2
    vitest: ^4.0.18
    vitest-package-exports: ^1.2.0
  types:
    '@types/node': ^25.3.5
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
